/*
Author Gaurav Sablok,
Email: codeprog@icloud.com
Date: 2025-5-14
*/

#[derive(Debug, Clone, PartialOrd, PartialEq)]
pub struct Genomecapture {
    pub version: String,
    pub filename: String,
    pub chr: String,
    pub start: String,
    pub end: String,
    pub generef: String,
    pub alt: String,
    pub effect: String,
    pub gene: String,
    pub transcript: String,
    pub selectcannonical: String,
    pub tfbsid: String,
    pub tfbsname: String,
    pub exonintronnum: String,
    pub hgvsc: String,
    pub hgvsp: String,
    pub cdsdistance: String,
    pub cdslen: String,
    pub aalen: String,
    pub othertranscripts: String,
    pub exac_an: String,
    pub exac_ac: String,
    pub exac_af: String,
    pub exac_istarget: String,
    pub dnsnp: String,
    pub dnsnp_version: String,
    pub dbsnp_1tgp_ref_freq: String,
    pub dbsnp_1tgp_alt_freq: String,
    pub common_1tgp_1perc: String,
    pub esp6500siv2_ea_freq: String,
    pub esp6500siv2_aa_freq: String,
    pub esp6500siv2_all_freq: String,
    pub gnomad_af_all: String,
    pub gnomad_hom_all: String,
    pub gnomad_af_max_pop: String,
    pub cadd_score: String,
    pub dbscsnv_ab_score: String,
    pub dbscsnv_rf_score: String,
    pub papi_pred: String,
    pub papi_score: String,
    pub polyphen_2_pred: String,
    pub polyphen_2_score: String,
    pub sift_pred: String,
    pub sift_score: String,
    pub pseeac_rf_pred: String,
    pub pseeac_rf_score: String,
    pub clinvar_hotspot: String,
    pub clinvar_rcv: String,
    pub clinvar_clinical_significance: String,
    pub clinvar_rev_status: String,
    pub clinical_traits: String,
    pub clinvar_traitsclinvar_pmids: String,
    pub diseases: String,
    pub disease_ids: String,
    pub geno: String,
    pub qual: String,
    pub geno_qual: String,
    pub genofilter: String,
    pub af: String,
    pub ao: String,
    pub ro: String,
    pub co: String,
}
